# Generated by Django 5.2.7 on 2025-10-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_date', models.DateField()),
                ('bill_no', models.CharField(max_length=200)),
                ('job_name', models.CharField(max_length=400)),
                ('company_name', models.CharField(max_length=500)),
                ('job_type', models.CharField(choices=[('new_job', 'New Job'), ('old_job', 'Old Job')], max_length=10)),
                ('noc', models.TextField(blank=True, null=True)),
                ('prpc_purchase', models.CharField(max_length=200)),
                ('prpc_sell', models.CharField(blank=True, max_length=200, null=True)),
                ('cylinder_size', models.CharField(max_length=200)),
                ('cylinder_made_in', models.CharField(max_length=200)),
                ('pouch_size', models.CharField(max_length=200)),
                ('pouch_open_size', models.CharField(max_length=200)),
                ('pouch_combination', models.CharField(max_length=200)),
                ('correction', models.TextField(blank=True, null=True)),
                ('folder_url', models.URLField()),
                ('image_links', models.CharField(blank=True, max_length=1000, null=True)),
                ('cylinder_date', models.DateField(blank=True, null=True)),
                ('cylinder_bill_no', models.CharField(blank=True, null=True)),
                ('job_status', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
