# Generated by Django 5.2.7 on 2025-10-16 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_jobdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetail',
            name='folder_url',
        ),
        migrations.RemoveField(
            model_name='jobdetail',
            name='image_links',
        ),
    ]
