# Generated by Django 5.2.7 on 2025-10-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_jobdetail_folder_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetail',
            name='bill_no',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='company_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='cylinder_made_in',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='cylinder_size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='job_name',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='pouch_combination',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='pouch_open_size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='pouch_size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobdetail',
            name='prpc_purchase',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
