# Generated by Django 5.2.7 on 2025-10-16 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_jobdetail_bill_no_alter_jobdetail_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetail',
            name='job_type',
            field=models.CharField(blank=True, choices=[('  ', 'New Job'), ('old_job', 'Old Job')], max_length=10, null=True),
        ),
    ]
