# Generated by Django 5.2.7 on 2025-10-16 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_jobdetail_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetail',
            name='job_type',
            field=models.CharField(blank=True, choices=[('new_job', 'New Job'), ('old_job', 'Old Job')], max_length=10, null=True),
        ),
    ]
