# Generated by Django 5.2.7 on 2025-10-16 10:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_jobdetail_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetail',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
